### ISSUE TITLE
IMAGE: add a CI image for new contributors

### ISSUE THREAD

**Issue by kierisi** [pyOpenSci/handbook#81]
from [this conversation:](https://github.com/pyOpenSci/handbook/pull/68#discussion_r1649422064)
* recreate this state in a repo
* take a screenshot
* update the handbook with the appropriate screenshot

**Comment by lwasser** [comment]
A contributor is anyone who contributes to a project who is not an owner. 

We have many people now in our org that have maintainer status that are contributors. They are contributors, but their status on the repo is really what drives what they see. Please consider that when you create the PR.
